version: '2.1'
services:
  tick-chronograf:
    container_name: ${CONTAINER_HOST_NAME:-standalone.tick}-chronograf
    environment:
      INFLUXDB_URL: http://${CONTAINER_HOST_NAME:-standalone.tick}-influxdb:${INFLUXDB_HTTP_API_PORT:-8086}
      KAPACITOR_URL: http://${CONTAINER_HOST_NAME:-standalone.tick}-kapacitor:${KAPACITOR_PORT:-9092}
      #RESOURCES_PATH: "/usr/share/chronograf/resources"
    hostname: ${CONTAINER_HOST_NAME:-standalone.tick}-chronograf
    image: ${IMAGE_NAME:-chronograf}:${IMAGE_TAG:-1.7.2}
    labels:
      deploy.config.commit: ${LABEL_DEPLOY_CONFIG_COMMIT:-unknown}
      deploy.config.name: ${LABEL_DEPLOY_CONFIG_NAME:-unknown}
      deploy.config.ref: ${LABEL_DEPLOY_CONFIG_REF:-unknown}
      deploy.util.commit: ${LABEL_DEPLOY_UTIL_COMMIT:-unknown}
      deploy.util.ref: ${LABEL_DEPLOY_UTIL_REF:-unknown}
      instance.name.short: ${LABEL_INSTANCE_NAME_SHORT:-standalone.tick-chronograf}
      instance.name: ${LABEL_INSTANCE_NAME:-127.0.0.1/tick-chronograf/standalone}
    networks:
      local-network:
        ipv4_address: ${IPV4_ADDRESS:-172.16.238.82}
        #ipv6_address: ${IPV6_ADDRESS:-2001:3984:3989::82}
    ports:
    - "${EXTERNAL_CHRONOGRAF_8888_PORT:-8083}:8888"
    restart: always
    volumes:
    - chronograf_data:/var/lib/chronograf


networks:
  local-network:
    external: true
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
      #- subnet: 2001:3984:3989::/64


volumes:
  chronograf_data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/var/lib/chronograf
      o: bind
